var ptr = window.publicMemoryObj.newobj(55)
console.log(ptr.value())
console.log(ptr.pointedTo())
console.log(ptr.point)
console.log(window.publicMemoryObj.valueOf(ptr.value()))
ptr.changeValue(96)
console.log(ptr.point)
window.publicMemoryObj.changeValue(ptr.value(), 96)
console.log(ptr.point)
console.log(window.publicMemoryObj)
