/* global memoryJS */
var ptr = memoryJS.publicMemoryObj.newobj(55)
console.log(ptr.isLocal())
console.log(ptr.value())
console.log(ptr.pointedTo())
console.log(ptr.point)
console.log(memoryJS.publicMemoryObj.valueOf(ptr.value()))
console.log(ptr.changeValue(96))
console.log(ptr.point = 96)
console.log(memoryJS.publicMemoryObj.changeValue(ptr.value(), 96))
console.log(ptr.point)
console.log(memoryJS.publicMemoryObj)
console.log(ptr.free())
